// <auto-generated />
using System;
using AnPhucNienSo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnPhucNienSo.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304014905_AddAuthAndMultiTenancy")]
    partial class AddAuthAndMultiTenancy
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnPhucNienSo.Api.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TempleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TempleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AnPhucNienSo.Api.Models.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("HeadOfHouseholdName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TempleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TempleId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("AnPhucNienSo.Api.Models.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("DharmaName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Gender")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TempleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TempleId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("AnPhucNienSo.Api.Models.PrayerRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("DonationAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TempleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("TempleId");

                    b.HasIndex("Year", "Type", "FamilyId")
                        .IsUnique();

                    b.ToTable("PrayerRecords");
                });

            modelBuilder.Entity("AnPhucNienSo.Api.Models.SystemConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Key");

                    b.ToTable("SystemConfigs");

                    b.HasData(
                        new
                        {
                            Key = "CurrentLunarYear",
                            Value = "2026"
                        });
                });

            modelBuilder.Entity("AnPhucNienSo.Api.Models.Temple", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Temples");
                });

            modelBuilder.Entity("AnPhucNienSo.Api.Models.Account", b =>
                {
                    b.HasOne("AnPhucNienSo.Api.Models.Temple", "Temple")
                        .WithMany("Accounts")
                        .HasForeignKey("TempleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Temple");
                });

            modelBuilder.Entity("AnPhucNienSo.Api.Models.Family", b =>
                {
                    b.HasOne("AnPhucNienSo.Api.Models.Temple", "Temple")
                        .WithMany("Families")
                        .HasForeignKey("TempleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Temple");
                });

            modelBuilder.Entity("AnPhucNienSo.Api.Models.Member", b =>
                {
                    b.HasOne("AnPhucNienSo.Api.Models.Family", "Family")
                        .WithMany("Members")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnPhucNienSo.Api.Models.Temple", "Temple")
                        .WithMany()
                        .HasForeignKey("TempleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Temple");
                });

            modelBuilder.Entity("AnPhucNienSo.Api.Models.PrayerRecord", b =>
                {
                    b.HasOne("AnPhucNienSo.Api.Models.Family", "Family")
                        .WithMany("PrayerRecords")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnPhucNienSo.Api.Models.Temple", "Temple")
                        .WithMany()
                        .HasForeignKey("TempleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("Temple");
                });

            modelBuilder.Entity("AnPhucNienSo.Api.Models.Family", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("PrayerRecords");
                });

            modelBuilder.Entity("AnPhucNienSo.Api.Models.Temple", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Families");
                });
#pragma warning restore 612, 618
        }
    }
}
